### ISSUE TITLE
hal json return type not parsed by browsers

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/clarity_slim#1]
Can we please provide a fallback to application/json when a browser is used to access the api?

**Comment by milovanderlinden** [comment]
If the Accept header is application/hal+json return Content-Type: application/hal+json
If the Accept header is application/json return Content-Type: application/json

**Comment by jgroenen** [comment]
For which browser doesn't this work?

**Comment by jgroenen** [comment]
It will now return "Content-Type:application/hal+json,application/json"
